### ISSUE TITLE
Switch back Rocket dependency to crates.io when 0.5 is released

### ISSUE THREAD

**Issue by HenningHolmDE** [lawliet89/rocket_cors#84]
Since PR #81 has been merged, the Rocket dependency is pulled from its GitHub master. When Rocket 0.5 is released, this should be switched back to the corresponding version on crates.io.

**Comment by WhoisDavid** [comment]
Would you consider pointing rocket to `{ git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev", default-features = false  }` now?

**Comment by HenningHolmDE** [comment]
I'm not sure if I understand this completely:
According to [the Cargo reference](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations), this version would be used for published crate versions. As currently, there is no version 0.5.0-dev [available on crates.io](https://crates.io/crates/rocket/versions), the dependency would be invalid.
What do I miss?

**Comment by WhoisDavid** [comment]
Sorry had a closer look. Just pasted this over wo thinking from [this issue](https://github.com/SergioBenitez/Rocket/issues/1476) on the rocket repo.
`0.5.0-dev` is the current version of Rocket in master (set in `Cargo.toml`) but not published to crates.io.

Should have looked further. This (git + version) is just a way to specify multiple deps locations (see [cargo reference](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations)). Bit like `patch.crates-io` I guess. 

I was actually getting the following warning:
```
warning: two git dependencies found for `https://github.com/SergioBenitez/Rocket` where one uses `branch = "master"` and the other doesn't; this will break in a future version of Cargo, so please ensure the dependency forms are consistent
```
and this is because I wasn't specifying `branch="master"` for rocket in my `Cargo.toml` whereas you do in the `Cargo.toml` of `rocket_cors`. 
This is all a bit confusing. Not sure what the best practice is to manage this and avoid conflicting deps.

My toml looks like this now and no warning:
```toml
[dependencies]
rocket = "0.5.0-dev"
rocket_cors = "0.5.2"

[dependencies.rocket_contrib]
version = "0.5.0-dev"
default-features = false
features = ["diesel_postgres_pool", "json"]

[patch.crates-io]
rocket = { git = 'https://github.com/SergioBenitez/Rocket', branch = "master" }
rocket_contrib = { git = 'https://github.com/SergioBenitez/Rocket', branch = "master" }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors.git", branch = "master" }
```
I basically needed to add this `branch = "master"` to get rid of the warning.
